const onlineProgramsData = [
    {
      title: "Web Development Bootcamp",
      img: "https://img.freepik.com/free-photo/graduation-cap-book-table_1340-27599.jpg?uid=R88795710&ga=GA1.1.347367071.1702385638&semt=ais_ai_generated",
      details: "A comprehensive bootcamp to learn full-stack web development.",
      duration: "12 weeks",
      level: "Intermediate",
      price: 1499.99,
      format: "Online",
      category: "Programming",
      status: "Active",
    },
    {
      title: "Digital Marketing Certification",
      img: "https://img.freepik.com/free-photo/3d-rendering-boy-playing-piano_23-2150898665.jpg?uid=R88795710&ga=GA1.1.347367071.1702385638&semt=ais_ai_generated",
      details: "Become a certified digital marketer and master online marketing strategies.",
      duration: "8 weeks",
      level: "Beginner",
      price: 899.99,
      format: "Online",
      category: "Marketing",
      status: "Active",
    },
    {
      title: "Data Science Masterclass",
      img: "https://img.freepik.com/free-photo/kids-futuristic-school-classroom_23-2150892840.jpg?uid=R88795710&ga=GA1.1.347367071.1702385638&semt=ais_ai_generated",
      details: "Unlock the power of data with our comprehensive data science masterclass.",
      duration: "16 weeks",
      level: "Advanced",
      price: 1999.99,
      format: "Online",
      category: "Data Science",
      status: "Active",
    },
    {
      title: "Graphic Design Fundamentals",
      img: "https://img.freepik.com/free-photo/kids-with-vr-glasses-abstract-futuristic-school-classroom_23-2150892648.jpg?uid=R88795710&ga=GA1.1.347367071.1702385638&semt=ais_ai_generated",
      details: "Learn the basics of graphic design and create stunning visual content.",
      duration: "6 weeks",
      level: "Beginner",
      price: 699.99,
      format: "Online",
      category: "Design",
      status: "Active",
    },
    {
      title: "Business Analytics Workshop",
      img: "https://img.freepik.com/free-photo/innovative-futuristic-classroom-students_23-2150906270.jpg?uid=R88795710&ga=GA1.1.347367071.1702385638&semt=ais_ai_generated",
      details: "Explore the world of business analytics and make data-driven decisions.",
      duration: "4 weeks",
      level: "Intermediate",
      price: 499.99,
      format: "Online",
      category: "Business",
      status: "Coming Soon",
    },
    {
      title: "Photography Essentials",
      img: "https://img.freepik.com/free-photo/human-hand-typing-computer-keyboard-night-generated-by-ai_188544-31050.jpg?uid=R88795710&ga=GA1.1.347367071.1702385638&semt=ais_ai_generated",
      details: "Master the essentials of photography and capture breathtaking moments.",
      duration: "10 weeks",
      level: "Beginner",
      price: 799.99,
      format: "Online",
      category: "Photography",
      status: "Active",
    },
  ];
  
  export default onlineProgramsData;
  