export enum tagTypes {
  student = "student",
  user = "user",
  moderator = "moderator",
  admin = "admin",
  trainer = "trainer",
  category = "category",
  milestone = "milestone",
  module = "module",
  lesson = "lesson",
  quiz = "quiz",
  course = "course",
  service = "service",
  booking = "booking",
  glossary = "glossary",
  faq = "faq",
  rating = "rating",
  resource = "resource",
  categoryChildren = "categoryChildren",
  
}

export const tagTypesList = [
  tagTypes.category,
  tagTypes.student,
  tagTypes.user,
  tagTypes.moderator,
  tagTypes.admin,
  tagTypes.trainer,
  tagTypes.milestone,
  tagTypes.module,
  tagTypes.lesson,
  tagTypes.quiz,
  tagTypes.faq,
  tagTypes.service,
  tagTypes.rating,
  tagTypes.rating,
  tagTypes.course,
  tagTypes.resource,
  tagTypes.glossary,
  tagTypes.categoryChildren,
];
