import "./globals.css";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import Providers from "@/lib/Providers";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Education Services",
//   description: "Generated by create next app",
// };
{/* <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"></meta> */}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
      <meta httpEquiv="Content-Security-Policy" content="upgrade-insecure-requests" />
        <body
          // className="container mx-auto "
          style={{
            boxShadow:
              "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
            maxWidth: "1990px",
            marginInline: "auto",
            padding: "5px",
          }}
        >
          <Providers>{children}</Providers>
        </body>
      </html>
    </Providers>
  );
}
