import "./globals.css";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import Providers from "@/lib/Providers";
import { Noto_Sans } from "next/font/google";

const inter = Noto_Sans({ subsets: ["latin"] ,weight:["400"]});

// export const metadata: Metadata = {
//   title: "Education Services",
//   description: "Generated by create next app",
// };
{
  /* <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"></meta> */
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <meta httpEquiv="Content-Security-Policy" content="upgrade-insecure-requests" />
        <body
          // className="container mx-auto "
          className={inter.className}
          
        >
          <Providers>{children}</Providers>
        </body>
      </html>
    </Providers>
  );
}
